// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Callback.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_Demo_CallbackReceiver_ids[2] =
{
    "::Demo::CallbackReceiver",
    "::Ice::Object"
};
const ::std::string iceC_Demo_CallbackReceiver_ops[] =
{
    "callback",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Demo_CallbackReceiver_callback_name = "callback";

const ::std::string iceC_Demo_CallbackSender_ids[2] =
{
    "::Demo::CallbackSender",
    "::Ice::Object"
};
const ::std::string iceC_Demo_CallbackSender_ops[] =
{
    "addClient",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Demo_CallbackSender_addClient_name = "addClient";

}

bool
Demo::CallbackReceiver::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_CallbackReceiver_ids, iceC_Demo_CallbackReceiver_ids + 2, s);
}

::std::vector<::std::string>
Demo::CallbackReceiver::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Demo_CallbackReceiver_ids[0], &iceC_Demo_CallbackReceiver_ids[2]);
}

::std::string
Demo::CallbackReceiver::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::CallbackReceiver::ice_staticId()
{
    static const ::std::string typeId = "::Demo::CallbackReceiver";
    return typeId;
}

/// \cond INTERNAL
bool
Demo::CallbackReceiver::_iceD_callback(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_num;
    istr->readAll(iceP_num);
    inS.endReadParams();
    this->callback(iceP_num, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
Demo::CallbackReceiver::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_CallbackReceiver_ops, iceC_Demo_CallbackReceiver_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_CallbackReceiver_ops)
    {
        case 0:
        {
            return _iceD_callback(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

bool
Demo::CallbackSender::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_CallbackSender_ids, iceC_Demo_CallbackSender_ids + 2, s);
}

::std::vector<::std::string>
Demo::CallbackSender::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Demo_CallbackSender_ids[0], &iceC_Demo_CallbackSender_ids[2]);
}

::std::string
Demo::CallbackSender::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::CallbackSender::ice_staticId()
{
    static const ::std::string typeId = "::Demo::CallbackSender";
    return typeId;
}

/// \cond INTERNAL
bool
Demo::CallbackSender::_iceD_addClient(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<CallbackReceiverPrx> iceP_receiver;
    istr->readAll(iceP_receiver);
    inS.endReadParams();
    this->addClient(::std::move(iceP_receiver), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
Demo::CallbackSender::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_CallbackSender_ops, iceC_Demo_CallbackSender_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_CallbackSender_ops)
    {
        case 0:
        {
            return _iceD_addClient(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
Demo::CallbackReceiverPrx::_iceI_callback(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_num, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Demo_CallbackReceiver_callback_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_num);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
Demo::CallbackReceiverPrx::_newInstance() const
{
    return ::IceInternal::createProxy<CallbackReceiverPrx>();
}
/// \endcond

const ::std::string&
Demo::CallbackReceiverPrx::ice_staticId()
{
    return CallbackReceiver::ice_staticId();
}

/// \cond INTERNAL
void
Demo::CallbackSenderPrx::_iceI_addClient(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<CallbackReceiverPrx>& iceP_receiver, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Demo_CallbackSender_addClient_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_receiver);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
Demo::CallbackSenderPrx::_newInstance() const
{
    return ::IceInternal::createProxy<CallbackSenderPrx>();
}
/// \endcond

const ::std::string&
Demo::CallbackSenderPrx::ice_staticId()
{
    return CallbackSender::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_Demo_CallbackReceiver_callback_name = "callback";

const ::std::string iceC_Demo_CallbackSender_addClient_name = "addClient";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Demo::upCast(CallbackReceiver* p) { return p; }

void
::IceProxy::Demo::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< CallbackReceiver>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new CallbackReceiver;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::Demo::CallbackReceiver::_iceI_begin_callback(::Ice::Int iceP_num, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Demo_CallbackReceiver_callback_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Demo_CallbackReceiver_callback_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_num);
        result->endWriteParams();
        result->invoke(iceC_Demo_CallbackReceiver_callback_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Demo::CallbackReceiver::end_callback(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Demo_CallbackReceiver_callback_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Demo::CallbackReceiver::_newInstance() const
{
    return new CallbackReceiver;
}
/// \endcond

const ::std::string&
IceProxy::Demo::CallbackReceiver::ice_staticId()
{
    return ::Demo::CallbackReceiver::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::Demo::upCast(CallbackSender* p) { return p; }

void
::IceProxy::Demo::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< CallbackSender>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new CallbackSender;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::Demo::CallbackSender::_iceI_begin_addClient(const ::Demo::CallbackReceiverPrx& iceP_receiver, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Demo_CallbackSender_addClient_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Demo_CallbackSender_addClient_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_receiver);
        result->endWriteParams();
        result->invoke(iceC_Demo_CallbackSender_addClient_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Demo::CallbackSender::end_addClient(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Demo_CallbackSender_addClient_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::Demo::CallbackSender::_newInstance() const
{
    return new CallbackSender;
}
/// \endcond

const ::std::string&
IceProxy::Demo::CallbackSender::ice_staticId()
{
    return ::Demo::CallbackSender::ice_staticId();
}

Demo::CallbackReceiver::~CallbackReceiver()
{
}

/// \cond INTERNAL
::Ice::Object* Demo::upCast(CallbackReceiver* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_Demo_CallbackReceiver_ids[2] =
{
    "::Demo::CallbackReceiver",
    "::Ice::Object"
};

}

bool
Demo::CallbackReceiver::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_CallbackReceiver_ids, iceC_Demo_CallbackReceiver_ids + 2, s);
}

::std::vector< ::std::string>
Demo::CallbackReceiver::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Demo_CallbackReceiver_ids[0], &iceC_Demo_CallbackReceiver_ids[2]);
}

const ::std::string&
Demo::CallbackReceiver::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::CallbackReceiver::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Demo::CallbackReceiver";
    return typeId;
#else
    return iceC_Demo_CallbackReceiver_ids[0];
#endif
}

/// \cond INTERNAL
bool
Demo::CallbackReceiver::_iceD_callback(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_num;
    istr->read(iceP_num);
    inS.endReadParams();
    this->callback(iceP_num, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_Demo_CallbackReceiver_all[] =
{
    "callback",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
Demo::CallbackReceiver::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_CallbackReceiver_all, iceC_Demo_CallbackReceiver_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_CallbackReceiver_all)
    {
        case 0:
        {
            return _iceD_callback(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
Demo::CallbackReceiver::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< CallbackReceiver, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Demo::CallbackReceiver::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< CallbackReceiver, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
Demo::_icePatchObjectPtr(CallbackReceiverPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = CallbackReceiverPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(CallbackReceiver::ice_staticId(), v);
    }
}
/// \endcond

Demo::CallbackSender::~CallbackSender()
{
}

/// \cond INTERNAL
::Ice::Object* Demo::upCast(CallbackSender* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_Demo_CallbackSender_ids[2] =
{
    "::Demo::CallbackSender",
    "::Ice::Object"
};

}

bool
Demo::CallbackSender::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Demo_CallbackSender_ids, iceC_Demo_CallbackSender_ids + 2, s);
}

::std::vector< ::std::string>
Demo::CallbackSender::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Demo_CallbackSender_ids[0], &iceC_Demo_CallbackSender_ids[2]);
}

const ::std::string&
Demo::CallbackSender::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Demo::CallbackSender::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Demo::CallbackSender";
    return typeId;
#else
    return iceC_Demo_CallbackSender_ids[0];
#endif
}

/// \cond INTERNAL
bool
Demo::CallbackSender::_iceD_addClient(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    CallbackReceiverPrx iceP_receiver;
    istr->read(iceP_receiver);
    inS.endReadParams();
    this->addClient(iceP_receiver, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_Demo_CallbackSender_all[] =
{
    "addClient",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
Demo::CallbackSender::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Demo_CallbackSender_all, iceC_Demo_CallbackSender_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Demo_CallbackSender_all)
    {
        case 0:
        {
            return _iceD_addClient(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
Demo::CallbackSender::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< CallbackSender, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Demo::CallbackSender::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< CallbackSender, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
Demo::_icePatchObjectPtr(CallbackSenderPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = CallbackSenderPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(CallbackSender::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
